### ISSUE TITLE
How to get the same pictures

### ISSUE THREAD

**Issue by Dementoris** [ByMykel/counter-strike-image-tracker#1]
Hey, man, we are currently working on our own CS2 server where we are using your site for skin changing. We wanted to ask you if it was possible to get the same pictures as you have for skins that aren't officially in CS2. We had worked out some way in which we could add skins on random weapons like, Tiger Tooth Desert Eagle, or Freehand Glock. We would like to implement these skins to your website but we couldn't figure out to get the same pictures as you have. We would be extremely grateful if you could help us. I am sorry that I am writing this into "Issues" but I couldn't find any other way to contact you. Thanks in advance for your response.

**Comment by ByMykel** [comment]
Hi, I am not sure if I have understood what your saying.

In this repo I have a simple script that downloads the images of items that are in game files. So I don't think you could do something similar to get images of items with patters that are not official.
