### ISSUE TITLE
Question...

### ISSUE THREAD

**Issue by Cutcorwn** [ByMykel/counter-strike-image-tracker#2]
Hey, do you know if it’s possible to create one like this to obtain the texture patterns?

**Comment by Cutcorwn** [comment]
I wanted to use the texture patterns of the skins for 3D renders, but I can't find them. I would like to know how to use them in my project

**Comment by ByMykel** [comment]
Hey @Cutcorwn. No idea, but following this comment in [reddit](https://www.reddit.com/r/GlobalOffensive/comments/bhm3f1/comment/eltxm1l/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) they migth be in `Steam\steamapps\common\Counter-Strike Global Offensive\game\csgo\pak01_dir`.

For example I have found this in `materials/models/weapons/customization/paints/antiqued/oiled_psd_1c4685c6.vtex_c`

![oiled_psd_1c4685c6](https://github.com/user-attachments/assets/edccc312-7cdd-43fa-ad36-fc71d35f1fcd)

So if this is what you are loking for you can adapt `vpkFolders` to check for `materials/models/weapons/customization` or something similar.

**Comment by Cutcorwn** [comment]
This is what I was looking for, thank you
