### ISSUE TITLE
How to Work with files on Limited Storage

### ISSUE THREAD

**Issue by S1nuxoff** [ByMykel/counter-strike-image-tracker#3]
Hi! I'm working on the exact same project as yours right now, only I'm optimizing it for Dota2. 
When I download all the files I get an error that there is no free space left. As I know there is only 14gb available on the virtual server. I don't understand how you have enough space to download all vpk, unzip them and commit.

**Comment by ByMykel** [comment]
Hi. Could it be because you are using a couple of `depotIds`?
>const depotIds = [381451, 381452, 381453, 381454, 381455, 373301];

What you can do is run this script locally and commit all the images. And then use this script to only commit the latest images added to the game.

**Comment by S1nuxoff** [comment]
I use multiple depotIds because the main depotId doesn't have all the vpk files. It is divided into several. 
And if I update only new images, will I still have to download all vpk in workflow?

I need to download 323 vpk. 

`Required VPK files: 1,2,3,5,7,9,10,12,13,14,17,18,19,21,23,24,25,29,30,32,35,47,48,49,50,51,52,53,55,56,63,66,67,80,81,82,83,91,95,96,100,102,106,107,108,109,110,111,112,113,114,115,116,117,118,121,122,125,126,127,128,130,131,133,134,135,136,137,140,141,143,145,146,147,148,150,151,152,153,154,155,157,158,166,167,170,171,173,174,175,177,178,180,181,182,184,185,187,188,191,192,193,195,196,197,198,199,200,201,203,204,205,206,207,208,212,214,215,216,217,218,219,220,221,223,226,227,228,229,230,231,234,235,236,237,239,240,241,243,244,246,251,253,254,255,257,258,260,261,262,263,265,267,268,269,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,288,289,290,291,292,294,295,296,298,299,301,302,303,305,306,307,310,312,313,314,315,316,319,320,323,324,326,328,329,330,331,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,349,350,351,353,355,359,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,378,379,380,381,382,383,384,385,386,387,389,391,392,393,394,395,396,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,439,441,442,445,446,448,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472`

```

const vpkFolders = [
  "panorama/images/econ/items",
  "panorama/images/econ/challenges",
  "panorama/images/econ/announcer",
  "panorama/images/econ/artifacts",
  "panorama/images/econ/bundles",
  "panorama/images/econ/casters",
  "panorama/images/econ/courier",
  "panorama/images/econ/crafting",
  "panorama/images/econ/creeps",
  "panorama/images/econ/cursor_pack",
  "panorama/images/econ/custom_games_pass",
  "panorama/images/econ/development",
  "panorama/images/econ/heroes",
  "panorama/images/econ/huds",
  "panorama/images/econ/items",
  "panorama/images/econ/leagues",
  "panorama/images/econ/loading_screens",
  "panorama/images/econ/music",
  "panorama/images/econ/pennant",
  "panorama/images/econ/pets",
  "panorama/images/econ/pins",
  "panorama/images/econ/props_gameplay",
  "panorama/images/econ/sets",
  "panorama/images/econ/sockets",
  "panorama/images/econ/taunts",
  "panorama/images/econ/terrain",
  "panorama/images/econ/tools",
  "panorama/images/econ/ui/treasure",
  "panorama/images/econ/voicepack",
  "panorama/images/econ/stickers",
  "panorama/images/econ/talentcontent",
  "panorama/images/econ/teamfancontent",
];
```

**Comment by ByMykel** [comment]
I am not sure but I'd say you don't need all of them to donwload the latest added images. It should be similar to this repo.

**Comment by S1nuxoff** [comment]
Okay, thanks for your help. I'll try to solve the problem.
